version: '3.8'

services:
  # PostgreSQL removed - using SQLite now
  # Keeping Redis for future caching needs
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: